# Name of website
title: Firmabiisit

# Your name to show in the footer
author: Mutjake

url-pretty: "firmabiisit.fi"

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
